-- Generated by Oracle SQL Developer Data Modeler 18.2.0.179.0756
--   at:        2021-01-28 21:42:14 CET
--   site:      SQL Server 2012
--   type:      SQL Server 2012

use master
go

drop database if exists Autoescuela2
go

create database Autoescuela2
go

use Autoescuela2
go

ALTER DATABASE Autoescuela2 
	ADD FILEGROUP [FileStream] 
	CONTAINS FILESTREAM 
GO
ALTER DATABASE Autoescuela2
       ADD FILE (
             NAME = 'Autoescuela_filestream',
             FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Autoescuela_FileStream'
       )
       TO FILEGROUP [FileStream]
GO

DROP TABLE IF EXISTS Imagenes
GO
CREATE TABLE imgs(
       id UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL UNIQUE,
       Imagen VARBINARY(MAX) FILESTREAM
);
GO


CREATE TABLE alumnos (
    id                    VARCHAR(20) NOT NULL,
    nombre                VARCHAR(50),
    apellidos             VARCHAR(50),
    clase_teorica_grupo   VARCHAR(10) NOT NULL,
    psicotecnico          bit NOT NULL
)

go

ALTER TABLE Alumnos ADD constraint alumnos_pk PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON ) 
go

CREATE TABLE clase_teorica 
    (
    grupo         VARCHAR(10) NOT NULL,
    hora_inicio   varchar(20),
    hora_fin VARCHAR(20),nºalumnos CHAR 
    ) 
go

ALTER TABLE Clase_Teorica ADD constraint clase_teorica_pk PRIMARY KEY CLUSTERED (Grupo)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON ) 
go

CREATE TABLE coches (
    matricula   VARCHAR(7) NOT NULL,
    modelo      VARCHAR(10),
    marca       VARCHAR(10)
)

go

ALTER TABLE Coches ADD constraint coches_pk PRIMARY KEY CLUSTERED (Matricula)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON ) 
go

CREATE TABLE examen_practico (
    examinador   VARCHAR(50) NOT NULL,
    fecha_hora   VARCHAR(20),
    fallos       INTEGER,
    alumnos_id   VARCHAR(20) NOT NULL
)

go 

CREATE unique nonclustered index examen_practico__idx ON examen_practico ( alumnos_id ) 
go

ALTER TABLE Examen_Practico ADD constraint examen_practico_pk PRIMARY KEY CLUSTERED (Examinador, Alumnos_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON ) 
go

CREATE TABLE examen_teorico (
    id_examen           VARCHAR(50) NOT NULL,
    fecha_hora_examen   VARCHAR(20),
    fallos              INTEGER,
    alumnos_id          VARCHAR(20) NOT NULL
)

go 

CREATE unique nonclustered index examen_teorico__idx ON examen_teorico ( alumnos_id ) 
go

ALTER TABLE Examen_Teorico ADD constraint examen_teorico_pk PRIMARY KEY CLUSTERED (ID_Examen, Alumnos_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON ) 
go

CREATE TABLE practica_coche (
    hora_inicio     VARCHAR(20),
    duracion        INTEGER,
    alumnos_id      VARCHAR(20) NOT NULL,
    profesores_id   VARCHAR(20) NOT NULL
)

go

ALTER TABLE Practica_Coche ADD constraint practica_coche_pk PRIMARY KEY CLUSTERED (Alumnos_ID, Profesores_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON ) 
go

CREATE TABLE profesores (
    id                 VARCHAR(20) NOT NULL,
    nombre             VARCHAR(50),
    apellidos          VARCHAR(50),
    coches_matricula   VARCHAR(7) NOT NULL
)

go 

CREATE unique nonclustered index profesores__idx ON profesores ( coches_matricula ) 
go

ALTER TABLE Profesores ADD constraint profesores_pk PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON ) 
go

ALTER TABLE Alumnos
    ADD CONSTRAINT alumnos_clase_teorica_fk FOREIGN KEY ( clase_teorica_grupo )
        REFERENCES clase_teorica ( grupo )
ON DELETE NO ACTION 
    ON UPDATE no action 
go

ALTER TABLE Examen_Practico
    ADD CONSTRAINT examen_practico_alumnos_fk FOREIGN KEY ( alumnos_id )
        REFERENCES alumnos ( id )
ON DELETE NO ACTION 
    ON UPDATE no action 
go

ALTER TABLE Examen_Teorico
    ADD CONSTRAINT examen_teorico_alumnos_fk FOREIGN KEY ( alumnos_id )
        REFERENCES alumnos ( id )
ON DELETE NO ACTION 
    ON UPDATE no action 
go

ALTER TABLE Practica_Coche
    ADD CONSTRAINT practica_coche_alumnos_fk FOREIGN KEY ( alumnos_id )
        REFERENCES alumnos ( id )
ON DELETE NO ACTION 
    ON UPDATE no action 
go

ALTER TABLE Practica_Coche
    ADD CONSTRAINT practica_coche_profesores_fk FOREIGN KEY ( profesores_id )
        REFERENCES profesores ( id )
ON DELETE NO ACTION 
    ON UPDATE no action 
go

ALTER TABLE Profesores
    ADD CONSTRAINT profesores_coches_fk FOREIGN KEY ( coches_matricula )
        REFERENCES coches ( matricula )
ON DELETE NO ACTION 
    ON UPDATE no action 
go



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             3
-- ALTER TABLE                             13
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
